[supervisord]
user=root
nodaemon=true
logfile=/var/log/supervisord/supervisord.log
pidfile=/var/run/supervisord/supervisord.pid
childlogdir=/var/log/supervisord/
logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
logfile_backups=10                              ; number of backed up logfiles
loglevel=error

[program:htsserver]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
user=%(ENV_PUID)s
command=/usr/bin/htsserver /usr/share/httrack/ --port %(ENV_PORT)s path %(ENV_DATA)s %(ENV_ARGS)s

[include]
files=/etc/supervisor.d/*.ini
